/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.GestorPersonas;
/**
 *
 * @author alumno
 */
public class EliminarPersona extends javax.swing.JFrame {
    private Menu principal;
    private GestorPersonas gestor;
    private DefaultTableModel modelo;
    /**
     * Creates new form EliminarPersona
     */
    public EliminarPersona(Menu p,GestorPersonas g) {
        initComponents();
        principal=p;
        gestor=g;
        principal.setVisible(false);
        this.setTitle("Eliminar registros de personas");
        
        String[] cab={"Apellido","Nombre","Edad"};
        
        modelo=new DefaultTableModel(cab,0);
        
        
        Object[] vec=new Object[3];
        
        int cant=gestor.cantPersonas();
        for(int i=0;i<cant;i++)
        {
            vec[0]=gestor.getPersona(i).getApellido();
            vec[1]=gestor.getPersona(i).getNombre();
            vec[2]=gestor.getPersona(i).getEdad();
            
            modelo.addRow(vec);
        }
        tablaPersonas.setModel(modelo);
        
        
        /*modelo=(DefaultTableModel)tablaPersonas.getModel();
        modelo.setColumnIdentifiers(cab);
        modelo.setRowCount(2);*/
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPersonas);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        /*tablaPersonas.getSelectedRow();
        modelo=(DefaultTableModel)tablaPersonas.getModel();
        modelo.setValueAt(tablaPersonas.getSelectedRow(), tablaPersonas.getSelectedRow(), 0);*/
        int fila=tablaPersonas.getSelectedRow();
        
        String ape=(String)modelo.getValueAt(fila, 0);
        String nom=(String)modelo.getValueAt(fila,1);
        int edad=(int)modelo.getValueAt(fila, 2);
        
        int resp=JOptionPane.showConfirmDialog(null, "¿Está seguro/a que desea eliminar el registro: "+ape+" - "+nom+" - "+edad+" ?");
        if(resp==JOptionPane.OK_OPTION)
        {
            modelo.removeRow(fila);
            gestor.removePersona(fila);
        }
        
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPersonas;
    // End of variables declaration//GEN-END:variables
}
