/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import negocio.GestorPersonas;
import negocio.Persona;

/**
 *
 * @author alumno
 */
public class ModificarPersona extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    private Menu principal;
    private GestorPersonas gestor;
    /**
     * Creates new form ModificarPersona
     */
    public ModificarPersona(Menu p,GestorPersonas g) {
        
        this.setTitle("Modificar personas registradas");
        initComponents();
        principal=p;
        principal.setVisible(false);
        gestor=g;
        
        int cant=gestor.cantPersonas();
        Object[][] mat=new Object[cant][5];
        Persona per=null;
        for(int i=0;i<cant;i++)
        {
            per=gestor.getPersona(i);
            if(per!=null)
            {
                mat[i][0]=per.getApellido();
                mat[i][1]=per.getNombre();
                mat[i][2]=per.getEdad();
                mat[i][3]=String.valueOf(per.getGenero());
                mat[i][4]=Arrays.toString(per.getPasatiempos());
            }
            /*mat[i][0]=gestor.getPersona(i).getApellido();
              mat[i][1]=gestor.getPersona(i).getNombre();
              mat[i][2]=gestor.getPersona(i).getEdad();
            */
        }
        modelo=(DefaultTableModel)tablaPersonas.getModel();
        Object[] cab={"Apellido","Nombre","Edad","Genero","Pasatiempo"};
        modelo.setDataVector(mat, cab);
        
        txtApellido.setEnabled(false);
        txtNombre.setEnabled(false);
        txtEdad.setEnabled(false);
        grupGenero.clearSelection();
        chkOtras.setEnabled(false);
        chkPasearMascota.setEnabled(false);
        chkPatinar.setEnabled(false);
        chkVerSeries.setEnabled(false);
        chkVideoJuegos.setEnabled(false);
        
        
    }
    
    public void limpiar()
    {
        tablaPersonas.setEnabled(true);
        txtApellido.setText("");
        txtNombre.setText("");
        txtEdad.setText("");
        tablaPersonas.clearSelection();
        txtApellido.setEnabled(false);
        txtNombre.setEnabled(false);
        txtEdad.setEnabled(false);

        grupGenero.clearSelection();
        chkOtras.setEnabled(false);
        chkPasearMascota.setEnabled(false);
        chkPatinar.setEnabled(false);
        chkVerSeries.setEnabled(false);
        chkVideoJuegos.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupGenero = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        rbtMasculino = new javax.swing.JRadioButton();
        rbtFemenino = new javax.swing.JRadioButton();
        chkVideoJuegos = new javax.swing.JCheckBox();
        chkPatinar = new javax.swing.JCheckBox();
        chkVerSeries = new javax.swing.JCheckBox();
        chkPasearMascota = new javax.swing.JCheckBox();
        chkOtras = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(tablaPersonas);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("Apellido:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Edad:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        grupGenero.add(rbtMasculino);
        rbtMasculino.setText("Masculino");

        grupGenero.add(rbtFemenino);
        rbtFemenino.setText("Femenino");

        chkVideoJuegos.setText("Video Juegoas");

        chkPatinar.setText("Patinar");

        chkVerSeries.setText("Ver Series");

        chkPasearMascota.setText("Pasear Mascota");

        chkOtras.setText("Otras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkVideoJuegos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkPatinar)
                                .addGap(18, 18, 18)
                                .addComponent(chkVerSeries)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkPasearMascota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkOtras))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSeleccionar)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2))
                                            .addComponent(jLabel3))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(rbtMasculino)
                                    .addComponent(rbtFemenino)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addGap(57, 57, 57)
                                .addComponent(btnCancelar)
                                .addGap(74, 74, 74)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSeleccionar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(rbtMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtFemenino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkVideoJuegos)
                    .addComponent(chkPatinar)
                    .addComponent(chkVerSeries)
                    .addComponent(chkPasearMascota)
                    .addComponent(chkOtras))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        txtApellido.setEnabled(true);
        txtNombre.setEnabled(true);
        txtEdad.setEnabled(true);

        grupGenero.clearSelection();
        chkOtras.setEnabled(true);
        chkPasearMascota.setEnabled(true);
        chkPatinar.setEnabled(true);
        chkVerSeries.setEnabled(true);
        chkVideoJuegos.setEnabled(true);
        rbtMasculino.setEnabled(true);
        rbtFemenino.setEnabled(true);
        
        int fila=tablaPersonas.getSelectedRow();
        if(fila>=0)
        {
            txtApellido.setText((String)modelo.getValueAt(fila, 0));
            txtNombre.setText((String)modelo.getValueAt(fila, 1));
            txtEdad.setText(String.valueOf(modelo.getValueAt(fila, 2)));
            if (String.valueOf(modelo.getValueAt(fila, 3))=="M") {
                rbtMasculino.setSelected(true);
            }else if (String.valueOf(modelo.getValueAt(fila, 3))=="F") {
                rbtFemenino.setSelected(true);
            }
                
            
            
        }
        tablaPersonas.setEnabled(false);
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String ape=txtApellido.getText();
        String nom=txtNombre.getText();
        int edad=Integer.parseInt(txtEdad.getText());
        char gen='x';
        if (rbtMasculino.isSelected()) {
            gen='M';
        }else if (rbtFemenino.isSelected()) {
            gen='F';
        }
        String[] pas=new String[4];
        if (chkVideoJuegos.isSelected()) {
            pas[0]="Video Juegos";
        }else if (chkPatinar.isSelected()) {
            pas[1]="Patinar";
        }else if (chkVerSeries.isSelected()) {
            pas[2]="Ver series";
        }else if (chkPasearMascota.isSelected()) {
            pas[3]="Pasear Mascota";
        }else if (chkOtras.isSelected()) {
            pas[4]="Otras";
        }
        
        
        //Persona per=new Persona(ape,nom,edad);
        int fila=tablaPersonas.getSelectedRow();
        modelo.setValueAt(ape, fila, 0);
        modelo.setValueAt(nom,fila,1);
        modelo.setValueAt(edad,fila,2);
        modelo.setValueAt(gen, fila, 3);
        
        gestor.modificarPersona(fila,ape,nom,edad,gen,pas);
        
        limpiar();
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JCheckBox chkOtras;
    private javax.swing.JCheckBox chkPasearMascota;
    private javax.swing.JCheckBox chkPatinar;
    private javax.swing.JCheckBox chkVerSeries;
    private javax.swing.JCheckBox chkVideoJuegos;
    private javax.swing.ButtonGroup grupGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtFemenino;
    private javax.swing.JRadioButton rbtMasculino;
    private javax.swing.JTable tablaPersonas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
